# Generated by Django 3.1.4 on 2021-01-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210113_0535'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
            ],
            options={
                'db_table': 'ProductImage',
            },
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='Inspirations',
            new_name='Inspiration',
        ),
        migrations.RenameModel(
            old_name='Mains',
            new_name='Main',
        ),
        migrations.RenameModel(
            old_name='Products_Spec',
            new_name='ProductService',
        ),
        migrations.RenameModel(
            old_name='ProductServices',
            new_name='ProductsSpecification',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Specifications',
            new_name='Specification',
        ),
        migrations.RenameModel(
            old_name='SubCategories',
            new_name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='productcolors',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcolors',
            name='product',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='video',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='imageurl',
        ),
        migrations.RemoveField(
            model_name='inspiration',
            name='slideimage_url',
        ),
        migrations.RemoveField(
            model_name='productservice',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='productsspecification',
            name='service',
        ),
        migrations.AddField(
            model_name='feature',
            name='video_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspiration',
            name='slide_image_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsspecification',
            name='specifications',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.specification'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='feature',
            table='feature',
        ),
        migrations.AlterModelTable(
            name='inspiration',
            table='inspiration',
        ),
        migrations.AlterModelTable(
            name='main',
            table='main',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productservice',
            table='productservice',
        ),
        migrations.AlterModelTable(
            name='productsspecification',
            table='ProductsSpecification',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
        migrations.AlterModelTable(
            name='specification',
            table='specification',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategory',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='ColorImages',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='ProductColors',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
