# Generated by Django 3.1.4 on 2021-01-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('giftwrapping', models.BooleanField()),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.RemoveField(
            model_name='carts',
            name='order',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='user',
        ),
        migrations.AlterField(
            model_name='giftwrapping',
            name='edition',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver')], default='Gold', max_length=6),
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='giftwrapping',
            table='giftwrapping',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
